###########################################################################
#
#   Makefile.libretro
#
#   Makefile for building MAME and derivatives as libretro core libraries
#
#   Copyright (C) 2015 Libretro Team.
#   Licensing should be regarded as the same as that of the MAME project,
#   visit http://mamedev.org for more information.
#
#
#   Okay, basically this file exists to do the following:
#
#   1. Determine $ARCH and $platform from the cmdline, the environment, or
#      by figuring them out (as other libretro cores do).
#   2. Disable -Werror.  MAME upstream builds with -Werror, which is great
#      for developers but absolutely frustrating for users.  From our POV,
#      we're effectively users, and users who try to follow the bleeding
#      edge no less.  That means we get cut, and too often it's by some
#      random warning upstream hasn't squashed.
#   3. Set PYTHON_EXECUTABLE.  Upstream assumes python (no prefix) is
#      python2.  Neither holds any more: python2 has been gone from the
#      build images for years, and an unversioned python is not installed
#      by default on Debian, Ubuntu or current macOS either.  python3 is
#      what is actually there, on every platform this core builds for.
#   4. Enable VERBOSE.  Yes, MAME builds generate a metric crap-ton of
#      output, but when builds fail it's nice to know why.
#   5. Rename $ARCH and unset it.  Apple has a convention on the Mac of
#      letting you use $ARCH to specify what CPU architectures to build
#      for.  This is at odds to how libretro uses it, and solving that on
#      the libretro end is going to have to wait for a major overhaul of
#      how cores are built.  We're not ready to do that yet.
#
###########################################################################

###########################################################################
#
#   LIBRETRO PREFERRED DEFAULT SETTINGS
#
###########################################################################

# Disable -Werror as libretro is effectively a MAME user, not a developer
NOWERROR ?= 1

# The generator scripts run under python3; python2 is not installed anywhere
# the buildbot builds this, and neither is an unversioned python.
PYTHON_EXECUTABLE ?= python3

# Cause the build system to regenerate itself, in case it changed
REGENIE ?= 1

# Spew much output developers need if MAME's build breaks for some reason
VERBOSE ?= 1

# You probably shouldn't need to set this anymore (find libretro section of
# scripts/toolchain.lua)
# PTR64 = 1

USE_BGFX ?= 0

# A libretro core plays its audio through the frontend, so neither of these
# is any use to us - and building them costs us portaudio's dependency on
# ALSA headers, which is one more thing that has to be present in every
# cross and 32-bit image we build in.
NO_USE_MIDI ?= 1
NO_USE_PORTAUDIO ?= 1

###########################################################################
#
#   LIBRETRO PLATFORM GUESSING
#
#   If the caller doesn't specify $platform and $ARCH, we guess
#
###########################################################################

UNAME_S = $(shell uname -s)
UNAME_M = $(shell uname -m)
ifeq ($(platform),)
	platform = unix
	ifeq ($(UNAME_S),)
		platform = win
	else ifneq ($(findstring MINGW,$(UNAME_S)),)
		platform = win
	else ifneq ($(findstring Darwin,$(UNAME_S)),)
		platform = osx
	else ifneq ($(findstring win,$(UNAME_S)),)
		platform = win
	endif
endif
ifneq ($(ARCH),)
	LIBRETRO_CPU = $(ARCH)
endif
ifeq ($(LIBRETRO_CPU),)
	ifeq ($(UNAME_M),)
		ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)
			LIBRETRO_CPU = x86_64
		endif
		ifeq ($(PROCESSOR_ARCHITEW6432),AMD64)
			LIBRETRO_CPU = x86_64
		endif
	else ifeq ($(UNAME_M),amd64)
		LIBRETRO_CPU = x86_64
	else
		LIBRETRO_CPU = $(UNAME_M)
	endif
endif

###########################################################################
#
#   LIBRETRO PLATFORM-SPECIFIC CONFIGURATION
#
#   Settings needed to get MAME to build everywhere we build it
#
###########################################################################

# Windows. The buildbot cross-builds these from Linux with the mxe
# toolchains: the templates hand us prefixed compilers in $CC/$CXX/$AR and
# the resource compiler in $WINDRES, which MAME wants as OVERRIDE_* instead,
# and TARGETOS has to be told - left alone MAME reads it off the build host
# and produces a Linux core with a .dll name. MAME also refuses to build
# either Windows target unless MINGW64/MINGW32 is set to something.
ifneq (,$(findstring win,$(platform)))
	TARGETOS = windows
	ifneq (,$(filter win32 x86,$(platform) $(LIBRETRO_CPU)))
		PTR64 = 0
		MINGW_FLAG = MINGW32=1
	else
		PTR64 = 1
		MINGW_FLAG = MINGW64=1
	endif
endif

# 32-bit desktops: MAME picks the target from PTR64, and the i686 Linux
# image is a native 32-bit rootfs, so this is all it takes there.
ifeq ($(LIBRETRO_CPU),x86)
	PTR64 = 0
endif

ifeq ($(platform), android)
#	PTR64 = 0
	# FIXME: Pass these to GENie and test...
#	CROSS_BUILD = 1
#	FORCE_DRC_C_BACKEND = 1
else ifeq ($(platform), osx)
	PYTHON_EXECUTABLE = python3
else ifneq (,$(findstring ios,$(platform)))
#	PTR64 = 0
        LIBRETRO_CPU=arm
	PYTHON_EXECUTABLE = python3
	# FIXME: Pass these to GENie and test...
#	CROSS_BUILD = 1
#	FORCE_DRC_C_BACKEND = 1
endif

ifneq (,$(findstring webos,$(CROSS_COMPILE)$(findstring starfish,$(CROSS_COMPILE))))
	PYTHON_EXECUTABLE = python3
	FORCE_DRC_C_BACKEND = 1
	ifneq (,$(findstring aarch64,$(CROSS_COMPILE)))
		PTR64 = 1
		CFLAGS += -DPTR64
		CXXFLAGS += -DPTR64
	else
		PTR64 = 0
	endif
endif

###########################################################################
#
#   BUILD FLAGS
#
###########################################################################

BUILDFLAGS = REGENIE=$(REGENIE) VERBOSE=$(VERBOSE) NOWERROR=$(NOWERROR) OSD="retro"
ifneq ($(NO_USE_MIDI),)
	BUILDFLAGS += NO_USE_MIDI=$(NO_USE_MIDI)
endif
ifneq ($(NO_USE_PORTAUDIO),)
	BUILDFLAGS += NO_USE_PORTAUDIO=$(NO_USE_PORTAUDIO)
endif
ifneq ($(PYTHON_EXECUTABLE),)
	BUILDFLAGS += PYTHON_EXECUTABLE=$(PYTHON_EXECUTABLE)
endif
ifeq ($(DEBUG),1)
	BUILDFLAGS += CONFIG=libretrodbg
else
	BUILDFLAGS += CONFIG=libretro
endif


###########################################################################
#
#   PLATFORM FLAGS
#
###########################################################################

PLATFLAGS =
ifneq ($(PTR64),)
	PLATFLAGS += PTR64=$(PTR64)
endif
ifneq ($(platform),)
	PLATFLAGS += LIBRETRO_OS="$(platform)"
endif
ifneq ($(TARGETOS),)
	PLATFLAGS += TARGETOS=$(TARGETOS)
endif
ifneq ($(MINGW_FLAG),)
	PLATFLAGS += $(MINGW_FLAG)
endif
# Forward the cross tools, but only the ones the caller actually set: CC and
# AR have make built-in defaults, and passing those along would override
# MAME's own choice on a native build.
ifneq (,$(filter environment command line,$(origin CC)))
	PLATFLAGS += OVERRIDE_CC="$(CC)"
endif
ifneq (,$(filter environment command line,$(origin CXX)))
	PLATFLAGS += OVERRIDE_CXX="$(CXX)"
endif
ifneq (,$(filter environment command line,$(origin AR)))
	PLATFLAGS += OVERRIDE_AR="$(AR)"
endif
ifneq (,$(filter environment command line,$(origin WINDRES)))
	PLATFLAGS += WINDRES="$(WINDRES)"
endif
ifeq ($(platform),win)
	ifeq ($(MSYSTEM),MINGW64)
		MINGW64 ?= /mingw64
		PLATFLAGS += MINGW64="$(MINGW64)"
	else ifeq ($(MSYSTEM),MINGW32)
		MINGW32 ?= /mingw32
		PLATFLAGS += MINGW32="$(MINGW32)"
	endif
endif
ifneq ($(LIBRETRO_CPU),)
	PLATFLAGS += ARCH="" LIBRETRO_CPU="$(LIBRETRO_CPU)"
endif
ifneq ($(FORCE_DRC_C_BACKEND),)
	PLATFLAGS += FORCE_DRC_C_BACKEND="$(FORCE_DRC_C_BACKEND)"
endif

###########################################################################
#
#   TARGET FLAGS
#
###########################################################################

TARGETFLAGS =
ifneq ($(TARGET),)
	TARGETFLAGS += TARGET=$(TARGET)
endif
ifneq ($(SUBTARGET),)
	TARGETFLAGS += SUBTARGET=$(SUBTARGET)
endif


###########################################################################
#
#   MAKE RULES
#
#   We just call upstream GENie here with appropriate args
#
###########################################################################

all: build

build:
	$(MAKE) $(BUILDFLAGS) $(PLATFLAGS) $(TARGETFLAGS)

clean:
	$(MAKE) $(BUILDFLAGS) $(PLATFLAGS) $(TARGETFLAGS) clean

.PHONY: all build clean
